networks:
  network:
    driver: bridge

volumes:
  postgres_data:
  
services:
    
  api:
    container_name: ModulBankAppAPI
    image: modulebank.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
    build:
      context: .
      dockerfile: ModuleBankApp.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
       - keycloak
       - db
  db:
    image: postgres:latest
    container_name: ModuleBankAppPostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ModuleBankAppDatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
      
  keycloak:
    container_name: ModuleBankAppKeycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./scripts/keycloak_setup.sh:/opt/keycloak/keycloak_setup.sh
    entrypoint: ["/bin/bash", "/opt/keycloak/keycloak_setup.sh"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HTTP_ENABLED: "true"
      KC_STRICT_HTTPS: "false"
       
    ports:
      - "8080:8080"
    networks:
      - network